version: 2 # CircleCI 2.0 version
jobs: # basic units of work in a run
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/SGA-hiromichi-sugawara/gitleaks

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache: 
          keys:
            - v1-pkg-cache
      
      - run:
          name: 単体テスト実行
          # テスト結果を$TEST_RESULTSディレクトリに保存します
          command: | 
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out

      - run: make # プロジェクトの依存関係をプルしてビルド            
      
      - save_cache: # キャッシュを/go/pkg ディレクトリに保存する
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
            
      - store_artifacts: # アーティファクト(https://circleci.com/docs/ja/2.0/artifacts/)に表示する為の処理
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # テストサマリーを(https://circleci.com/docs/ja/2.0/collect-test-data/)に保存する処理
          path: /tmp/test-results
